// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace OpenCertServer.CertServer.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "caa-rfc8657")]
    public partial class RFC8657CAAAccountURIAndValidationMethodBindingFeature : object, Xunit.IClassFixture<RFC8657CAAAccountURIAndValidationMethodBindingFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = new string[] {
                "caa-rfc8657"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "RFC 8657 CAA account URI and validation method binding", "    RFC 8657 defines the \"accounturi\" and \"validationmethods\" parameters on\n    C" +
                "AA \"issue\" and \"issuewild\" properties, refining which ACME account and\n    which" +
                " validation method a CA may use to authorize issuance.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "AcmeCaaRfc8657.feature"
#line hidden
        
        public RFC8657CAAAccountURIAndValidationMethodBindingFeature(RFC8657CAAAccountURIAndValidationMethodBindingFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/AcmeCaaRfc8657.feature.ndjson", 20);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="a matching accounturi authorizes issuance")]
        [global::Xunit.TraitAttribute("FeatureTitle", "RFC 8657 CAA account URI and validation method binding")]
        [global::Xunit.TraitAttribute("Description", "a matching accounturi authorizes issuance")]
        public async global::System.Threading.Tasks.Task AMatchingAccounturiAuthorizesIssuance()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("a matching accounturi authorizes issuance", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the accounturi parameter restricts issuance to a specific ACME account", null, tagsOfRule);
#line 10
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
            await testRunner.GivenAsync("a CAA \"issue\" record for \"example.com\" authorizing \"ca.example.com\" with the para" +
                        "meter \"accounturi=https://acme.example.com/account/1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
            await testRunner.AndAsync("the ACME request uses the account \"https://acme.example.com/account/1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
            await testRunner.AndAsync("the validation method \"dns-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
            await testRunner.WhenAsync("CAA validation runs for \"example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
            await testRunner.ThenAsync("the CAA validation must authorize issuance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="a non-matching accounturi prevents authorization")]
        [global::Xunit.TraitAttribute("FeatureTitle", "RFC 8657 CAA account URI and validation method binding")]
        [global::Xunit.TraitAttribute("Description", "a non-matching accounturi prevents authorization")]
        public async global::System.Threading.Tasks.Task ANon_MatchingAccounturiPreventsAuthorization()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("a non-matching accounturi prevents authorization", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the accounturi parameter restricts issuance to a specific ACME account", null, tagsOfRule);
#line 17
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
            await testRunner.GivenAsync("a CAA \"issue\" record for \"example.com\" authorizing \"ca.example.com\" with the para" +
                        "meter \"accounturi=https://acme.example.com/account/0000\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
            await testRunner.AndAsync("the ACME request uses the account \"https://acme.example.com/account/1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
            await testRunner.AndAsync("the validation method \"dns-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
            await testRunner.WhenAsync("CAA validation runs for \"example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
            await testRunner.ThenAsync("the CAA validation must reject issuance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="an accounturi with an equivalent trailing slash is still a match")]
        [global::Xunit.TraitAttribute("FeatureTitle", "RFC 8657 CAA account URI and validation method binding")]
        [global::Xunit.TraitAttribute("Description", "an accounturi with an equivalent trailing slash is still a match")]
        public async global::System.Threading.Tasks.Task AnAccounturiWithAnEquivalentTrailingSlashIsStillAMatch()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("an accounturi with an equivalent trailing slash is still a match", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the accounturi parameter restricts issuance to a specific ACME account", null, tagsOfRule);
#line 24
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
            await testRunner.GivenAsync("a CAA \"issue\" record for \"example.com\" authorizing \"ca.example.com\" with the para" +
                        "meter \"accounturi=https://acme.example.com/account/1234/\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
            await testRunner.AndAsync("the ACME request uses the account \"https://acme.example.com/account/1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
            await testRunner.AndAsync("the validation method \"dns-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
            await testRunner.WhenAsync("CAA validation runs for \"example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
            await testRunner.ThenAsync("the CAA validation must authorize issuance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="multiple accounturi parameters make the property unsatisfiable")]
        [global::Xunit.TraitAttribute("FeatureTitle", "RFC 8657 CAA account URI and validation method binding")]
        [global::Xunit.TraitAttribute("Description", "multiple accounturi parameters make the property unsatisfiable")]
        public async global::System.Threading.Tasks.Task MultipleAccounturiParametersMakeThePropertyUnsatisfiable()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("multiple accounturi parameters make the property unsatisfiable", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the accounturi parameter restricts issuance to a specific ACME account", null, tagsOfRule);
#line 31
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 32
            await testRunner.GivenAsync("a CAA \"issue\" record for \"example.com\" authorizing \"ca.example.com\" with the para" +
                        "meters \"accounturi=https://acme.example.com/account/1234;accounturi=https://acme" +
                        ".example.com/account/5678\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 33
            await testRunner.AndAsync("the ACME request uses the account \"https://acme.example.com/account/1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
            await testRunner.AndAsync("the validation method \"dns-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
            await testRunner.WhenAsync("CAA validation runs for \"example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 36
            await testRunner.ThenAsync("the CAA validation must reject issuance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="an invalid accounturi makes the property unsatisfiable")]
        [global::Xunit.TraitAttribute("FeatureTitle", "RFC 8657 CAA account URI and validation method binding")]
        [global::Xunit.TraitAttribute("Description", "an invalid accounturi makes the property unsatisfiable")]
        public async global::System.Threading.Tasks.Task AnInvalidAccounturiMakesThePropertyUnsatisfiable()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("an invalid accounturi makes the property unsatisfiable", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the accounturi parameter restricts issuance to a specific ACME account", null, tagsOfRule);
#line 38
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
            await testRunner.GivenAsync("a CAA \"issue\" record for \"example.com\" authorizing \"ca.example.com\" with the para" +
                        "meter \"accounturi=not-a-uri\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
            await testRunner.AndAsync("the ACME request uses the account \"https://acme.example.com/account/1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
            await testRunner.AndAsync("the validation method \"dns-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
            await testRunner.WhenAsync("CAA validation runs for \"example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
            await testRunner.ThenAsync("the CAA validation must reject issuance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="an accounturi cannot be satisfied when the account URI is unknown")]
        [global::Xunit.TraitAttribute("FeatureTitle", "RFC 8657 CAA account URI and validation method binding")]
        [global::Xunit.TraitAttribute("Description", "an accounturi cannot be satisfied when the account URI is unknown")]
        public async global::System.Threading.Tasks.Task AnAccounturiCannotBeSatisfiedWhenTheAccountURIIsUnknown()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("an accounturi cannot be satisfied when the account URI is unknown", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the accounturi parameter restricts issuance to a specific ACME account", null, tagsOfRule);
#line 45
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 46
            await testRunner.GivenAsync("a CAA \"issue\" record for \"example.com\" authorizing \"ca.example.com\" with the para" +
                        "meter \"accounturi=https://acme.example.com/account/1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 47
            await testRunner.AndAsync("the validation method \"dns-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
            await testRunner.WhenAsync("CAA validation runs for \"example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
            await testRunner.ThenAsync("the CAA validation must reject issuance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="a property without accounturi matches any account")]
        [global::Xunit.TraitAttribute("FeatureTitle", "RFC 8657 CAA account URI and validation method binding")]
        [global::Xunit.TraitAttribute("Description", "a property without accounturi matches any account")]
        public async global::System.Threading.Tasks.Task APropertyWithoutAccounturiMatchesAnyAccount()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("a property without accounturi matches any account", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the accounturi parameter restricts issuance to a specific ACME account", null, tagsOfRule);
#line 51
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 52
            await testRunner.GivenAsync("a CAA \"issue\" record for \"example.com\" authorizing \"ca.example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 53
            await testRunner.AndAsync("the ACME request uses the account \"https://acme.example.com/account/1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
            await testRunner.AndAsync("the validation method \"dns-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
            await testRunner.WhenAsync("CAA validation runs for \"example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 56
            await testRunner.ThenAsync("the CAA validation must authorize issuance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="a listed validation method authorizes issuance")]
        [global::Xunit.TraitAttribute("FeatureTitle", "RFC 8657 CAA account URI and validation method binding")]
        [global::Xunit.TraitAttribute("Description", "a listed validation method authorizes issuance")]
        public async global::System.Threading.Tasks.Task AListedValidationMethodAuthorizesIssuance()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("a listed validation method authorizes issuance", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the validationmethods parameter restricts the allowed validation methods", null, tagsOfRule);
#line 60
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 61
            await testRunner.GivenAsync("a CAA \"issue\" record for \"example.com\" authorizing \"ca.example.com\" with the para" +
                        "meter \"validationmethods=dns-01,http-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 62
            await testRunner.AndAsync("the validation method \"dns-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
            await testRunner.WhenAsync("CAA validation runs for \"example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
            await testRunner.ThenAsync("the CAA validation must authorize issuance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="an unlisted validation method prevents authorization")]
        [global::Xunit.TraitAttribute("FeatureTitle", "RFC 8657 CAA account URI and validation method binding")]
        [global::Xunit.TraitAttribute("Description", "an unlisted validation method prevents authorization")]
        public async global::System.Threading.Tasks.Task AnUnlistedValidationMethodPreventsAuthorization()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("an unlisted validation method prevents authorization", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the validationmethods parameter restricts the allowed validation methods", null, tagsOfRule);
#line 66
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 67
            await testRunner.GivenAsync("a CAA \"issue\" record for \"example.com\" authorizing \"ca.example.com\" with the para" +
                        "meter \"validationmethods=dns-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 68
            await testRunner.AndAsync("the validation method \"http-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
            await testRunner.WhenAsync("CAA validation runs for \"example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
            await testRunner.ThenAsync("the CAA validation must reject issuance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="validation method labels are matched case-insensitively")]
        [global::Xunit.TraitAttribute("FeatureTitle", "RFC 8657 CAA account URI and validation method binding")]
        [global::Xunit.TraitAttribute("Description", "validation method labels are matched case-insensitively")]
        public async global::System.Threading.Tasks.Task ValidationMethodLabelsAreMatchedCase_Insensitively()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("validation method labels are matched case-insensitively", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the validationmethods parameter restricts the allowed validation methods", null, tagsOfRule);
#line 72
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 73
            await testRunner.GivenAsync("a CAA \"issue\" record for \"example.com\" authorizing \"ca.example.com\" with the para" +
                        "meter \"validationmethods=DNS-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 74
            await testRunner.AndAsync("the validation method \"dns-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
            await testRunner.WhenAsync("CAA validation runs for \"example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 76
            await testRunner.ThenAsync("the CAA validation must authorize issuance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="the BR alternative label for the website-ACME method authorizes http-01")]
        [global::Xunit.TraitAttribute("FeatureTitle", "RFC 8657 CAA account URI and validation method binding")]
        [global::Xunit.TraitAttribute("Description", "the BR alternative label for the website-ACME method authorizes http-01")]
        public async global::System.Threading.Tasks.Task TheBRAlternativeLabelForTheWebsite_ACMEMethodAuthorizesHttp_01()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("the BR alternative label for the website-ACME method authorizes http-01", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the validationmethods parameter restricts the allowed validation methods", null, tagsOfRule);
#line 78
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 79
            await testRunner.GivenAsync("a CAA \"issue\" record for \"example.com\" authorizing \"ca.example.com\" with the para" +
                        "meter \"validationmethods=ca-tbr-19\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 80
            await testRunner.AndAsync("the validation method \"http-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
            await testRunner.WhenAsync("CAA validation runs for \"example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 82
            await testRunner.ThenAsync("the CAA validation must authorize issuance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="the BR alternative label for the DNS-change method authorizes dns-01")]
        [global::Xunit.TraitAttribute("FeatureTitle", "RFC 8657 CAA account URI and validation method binding")]
        [global::Xunit.TraitAttribute("Description", "the BR alternative label for the DNS-change method authorizes dns-01")]
        public async global::System.Threading.Tasks.Task TheBRAlternativeLabelForTheDNS_ChangeMethodAuthorizesDns_01()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("the BR alternative label for the DNS-change method authorizes dns-01", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the validationmethods parameter restricts the allowed validation methods", null, tagsOfRule);
#line 84
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 85
            await testRunner.GivenAsync("a CAA \"issue\" record for \"example.com\" authorizing \"ca.example.com\" with the para" +
                        "meter \"validationmethods=ca-tbr-7\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 86
            await testRunner.AndAsync("the validation method \"dns-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 87
            await testRunner.WhenAsync("CAA validation runs for \"example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 88
            await testRunner.ThenAsync("the CAA validation must authorize issuance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="the BR alternative label for another method prevents authorization")]
        [global::Xunit.TraitAttribute("FeatureTitle", "RFC 8657 CAA account URI and validation method binding")]
        [global::Xunit.TraitAttribute("Description", "the BR alternative label for another method prevents authorization")]
        public async global::System.Threading.Tasks.Task TheBRAlternativeLabelForAnotherMethodPreventsAuthorization()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("the BR alternative label for another method prevents authorization", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the validationmethods parameter restricts the allowed validation methods", null, tagsOfRule);
#line 90
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 91
            await testRunner.GivenAsync("a CAA \"issue\" record for \"example.com\" authorizing \"ca.example.com\" with the para" +
                        "meter \"validationmethods=ca-tbr-7\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 92
            await testRunner.AndAsync("the validation method \"http-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 93
            await testRunner.WhenAsync("CAA validation runs for \"example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 94
            await testRunner.ThenAsync("the CAA validation must reject issuance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="a property without validationmethods allows any validation method")]
        [global::Xunit.TraitAttribute("FeatureTitle", "RFC 8657 CAA account URI and validation method binding")]
        [global::Xunit.TraitAttribute("Description", "a property without validationmethods allows any validation method")]
        public async global::System.Threading.Tasks.Task APropertyWithoutValidationmethodsAllowsAnyValidationMethod()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("a property without validationmethods allows any validation method", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the validationmethods parameter restricts the allowed validation methods", null, tagsOfRule);
#line 96
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 97
            await testRunner.GivenAsync("a CAA \"issue\" record for \"example.com\" authorizing \"ca.example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 98
            await testRunner.AndAsync("the validation method \"tls-alpn-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 99
            await testRunner.WhenAsync("CAA validation runs for \"example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 100
            await testRunner.ThenAsync("the CAA validation must authorize issuance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="both parameters must be satisfied together")]
        [global::Xunit.TraitAttribute("FeatureTitle", "RFC 8657 CAA account URI and validation method binding")]
        [global::Xunit.TraitAttribute("Description", "both parameters must be satisfied together")]
        public async global::System.Threading.Tasks.Task BothParametersMustBeSatisfiedTogether()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("both parameters must be satisfied together", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the accounturi and validationmethods parameters combine", null, tagsOfRule);
#line 104
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 105
            await testRunner.GivenAsync("a CAA \"issue\" record for \"example.com\" authorizing \"ca.example.com\" with the para" +
                        "meter \"accounturi=https://acme.example.com/account/1234; validationmethods=dns-0" +
                        "1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 106
            await testRunner.AndAsync("the ACME request uses the account \"https://acme.example.com/account/1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 107
            await testRunner.AndAsync("the validation method \"dns-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 108
            await testRunner.WhenAsync("CAA validation runs for \"example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 109
            await testRunner.ThenAsync("the CAA validation must authorize issuance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="a method restriction applies even when the account matches")]
        [global::Xunit.TraitAttribute("FeatureTitle", "RFC 8657 CAA account URI and validation method binding")]
        [global::Xunit.TraitAttribute("Description", "a method restriction applies even when the account matches")]
        public async global::System.Threading.Tasks.Task AMethodRestrictionAppliesEvenWhenTheAccountMatches()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("a method restriction applies even when the account matches", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the accounturi and validationmethods parameters combine", null, tagsOfRule);
#line 111
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 112
            await testRunner.GivenAsync("a CAA \"issue\" record for \"example.com\" authorizing \"ca.example.com\" with the para" +
                        "meter \"accounturi=https://acme.example.com/account/1234; validationmethods=dns-0" +
                        "1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 113
            await testRunner.AndAsync("the ACME request uses the account \"https://acme.example.com/account/1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 114
            await testRunner.AndAsync("the validation method \"http-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 115
            await testRunner.WhenAsync("CAA validation runs for \"example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 116
            await testRunner.ThenAsync("the CAA validation must reject issuance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="an authorizing property supersedes a restricting property")]
        [global::Xunit.TraitAttribute("FeatureTitle", "RFC 8657 CAA account URI and validation method binding")]
        [global::Xunit.TraitAttribute("Description", "an authorizing property supersedes a restricting property")]
        public async global::System.Threading.Tasks.Task AnAuthorizingPropertySupersedesARestrictingProperty()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("an authorizing property supersedes a restricting property", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("any matching property in the RRset authorizes issuance", null, tagsOfRule);
#line 120
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 121
            await testRunner.GivenAsync("a CAA \"issue\" record for \"example.com\" authorizing \"ca.example.com\" with the para" +
                        "meter \"validationmethods=http-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 122
            await testRunner.AndAsync("a CAA \"issue\" record for \"example.com\" authorizing \"ca.example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 123
            await testRunner.AndAsync("the validation method \"dns-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
            await testRunner.WhenAsync("CAA validation runs for \"example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 125
            await testRunner.ThenAsync("the CAA validation must authorize issuance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="an empty issuer property does not authorize any CA")]
        [global::Xunit.TraitAttribute("FeatureTitle", "RFC 8657 CAA account URI and validation method binding")]
        [global::Xunit.TraitAttribute("Description", "an empty issuer property does not authorize any CA")]
        public async global::System.Threading.Tasks.Task AnEmptyIssuerPropertyDoesNotAuthorizeAnyCA()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("an empty issuer property does not authorize any CA", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("any matching property in the RRset authorizes issuance", null, tagsOfRule);
#line 127
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 128
            await testRunner.GivenAsync("a CAA \"issue\" record for \"example.com\" with an empty issuer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 129
            await testRunner.AndAsync("the validation method \"dns-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 130
            await testRunner.WhenAsync("CAA validation runs for \"example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 131
            await testRunner.ThenAsync("the CAA validation must reject issuance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await RFC8657CAAAccountURIAndValidationMethodBindingFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await RFC8657CAAAccountURIAndValidationMethodBindingFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
