using System.Net;
using System.Text.Json.Serialization;

namespace CertesSlim.Acme.Resource;

/// <summary>
/// Represents the ACME Order resource.
/// </summary>
public class Order
{
    /// <summary>
    /// Gets or sets the status.
    /// </summary>
    /// <value>
    /// The status.
    /// </value>
    /// <remarks>
    /// See <see cref="OrderStatus"/> for possible values.
    /// </remarks>
    [JsonPropertyName("status")]
    public OrderStatus? Status { get; set; }

    /// <summary>
    /// Gets or sets the expires.
    /// </summary>
    /// <value>
    /// The expires.
    /// </value>
    [JsonPropertyName("expires")]
    public DateTimeOffset? Expires { get; set; }

    /// <summary>
    /// Gets or sets the identifiers.
    /// </summary>
    /// <value>
    /// The identifiers.
    /// </value>
    public IList<Identifier>? Identifiers { get; set; }

    /// <summary>
    /// Gets or sets the not before.
    /// </summary>
    /// <value>
    /// The not before.
    /// </value>
    [JsonPropertyName("notBefore")]
    public DateTimeOffset? NotBefore { get; set; }

    /// <summary>
    /// Gets or sets the not after.
    /// </summary>
    /// <value>
    /// The not after.
    /// </value>
    [JsonPropertyName("notAfter")]
    public DateTimeOffset? NotAfter { get; set; }

    /// <summary>
    /// Gets or sets the error.
    /// </summary>
    /// <value>
    /// The error.
    /// </value>
    [JsonPropertyName("error")]
    public ErrorDetails? Error { get; set; }

    /// <summary>
    /// Gets or sets the authorizations.
    /// </summary>
    /// <value>
    /// The authorizations.
    /// </value>
    [JsonPropertyName("authorizations")]
    public IList<Uri>? Authorizations { get; set; }

    /// <summary>
    /// Gets or sets the finalize.
    /// </summary>
    /// <value>
    /// The finalize.
    /// </value>
    [JsonPropertyName("finalize")]
    public Uri? Finalize { get; set; }

    /// <summary>
    /// Gets or sets the certificate.
    /// </summary>
    /// <value>
    /// The certificate.
    /// </value>
    [JsonPropertyName("certificate")]
    public Uri? Certificate { get; set; }

    /// <summary>
    /// Represents the payload to finalize an order.
    /// </summary>
    /// <seealso cref="Order" />
    internal class OrderPayload : Order
    {
        /// <summary>
        /// Gets or sets the CSR.
        /// </summary>
        /// <value>
        /// The CSR.
        /// </value>
        [JsonPropertyName("csr")]
        public required string Csr { get; set; }
    }
}

/// <summary>
/// A machine-readable format for specifying errors in HTTP API responses based on https://tools.ietf.org/html/rfc7807.
/// </summary>
public sealed record ErrorDetails
{
    /// <summary>
    /// A short, human-readable summary of the problem type.It SHOULD NOT change from occurrence to occurrence
    /// of the problem, except for purposes of localization(e.g., using proactive content negotiation;
    /// see[RFC7231], Section 3.4).
    /// </summary>
    [JsonPropertyName("error"), JsonRequired]
    public required string Title { get; set; }

    /// <summary>
    /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
    /// </summary>
    [JsonPropertyName("status")]
    public HttpStatusCode Status { get; set; } = HttpStatusCode.BadRequest;

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    [JsonPropertyName("detail")]
    public required string Detail { get; set; }

    /// <inheritdoc />
    public override string ToString()
    {
        return $"{Title} - {Detail.Replace('\n', ' ').Replace("\r", string.Empty)} - {Status}";
    }
}
