using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using NSubstitute;
using OpenCertServer.Attestation;
using OpenCertServer.Attestation.Native;
using OpenCertServer.Attestation.Tests.Mocks;
using Reqnroll;

[Binding]
public class AppleSeAttestationSteps
{
    private readonly IHttpClientFactory _httpFactoryMock = Substitute.For<IHttpClientFactory>();
    private readonly ILogger<AppleSeProvider> _loggerMock = Substitute.For<ILogger<AppleSeProvider>>();
    private readonly IAppleAttestNativeInterop _nativeMock = Substitute.For<IAppleAttestNativeInterop>();
    private AppleSeProvider? _provider;
    private byte[]? _result;

    [Given(@"an attestation object generated by the iOS device")]
    public void GivenAnAttestationObjectGeneratedByTheIosDevice()
    {
        // The provider is configured in server-side verification mode (UseDeviceAttestation = false),
        // so it always routes through the HTTP verification path regardless of the host OS.
    }

    [When(@"sent to the OpenCertServer for verification")]
    public async Task WhenSentToTheOpenCertServerForVerification()
    {
        var verificationToken = new byte[] { 0x01, 0x02, 0x03, 0x04 };
        var mockResponse = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new ByteArrayContent(verificationToken)
        };
        var client = new HttpClient(new MockHttpHandler(mockResponse));
        _httpFactoryMock.CreateClient(nameof(AppleSeProvider)).Returns(client);

        var options = Options.Create(new AttestationOptions
        {
            AppleSE = new AppleSeOptions
            {
                VerifyUrl = "https://appattest.apple.com",
                TeamId = "TESTTEAM01",
                AppId = "com.opencert.server",
                UseDeviceAttestation = false  // server-side verification path
            }
        });
        _provider = new AppleSeProvider(_httpFactoryMock, _loggerMock, _nativeMock, options);

        // nonce = simulated attestation object bytes from the iOS client
        var attestationObject = new byte[512];
        Random.Shared.NextBytes(attestationObject);
        _result = await _provider.GenerateAndSignQuoteAsync(null!, attestationObject);
    }

    [Then(@"the server should successfully verify the object using https:\/\/appattest\.apple\.com and confirm device genuineness")]
    public void ThenTheServerShouldVerify()
    {
        if (_result is null || _result.Length == 0)
            throw new Exception("Expected a non-empty verification token from Apple");
    }
}
