using System.Net;
using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using NSubstitute;
using OpenCertServer.Attestation;
using OpenCertServer.Attestation.Native;
using OpenCertServer.Attestation.Tests.Mocks;
using Reqnroll;

[Binding]
public class AppleSeAttestationSteps : IDisposable
{
    private readonly IHttpClientFactory _httpFactoryMock = Substitute.For<IHttpClientFactory>();
    private readonly ILogger<AppleSeProvider> _loggerMock = Substitute.For<ILogger<AppleSeProvider>>();
    private AppleSeProvider? _provider;
    // Real interop used on Apple platforms; owned by this instance.
    private SecurityFrameworkAppleAttestInterop? _realNative;
    private byte[]? _result;

    [Given(@"an attestation object generated by the iOS device")]
    public void GivenAnAttestationObjectGeneratedByTheIosDevice()
    {
        // No setup needed here — the When step configures the right mode.
    }

    [When(@"sent to the OpenCertServer for verification")]
    public async Task WhenSentToTheOpenCertServerForVerification()
    {
        bool useDeviceAttestation = OperatingSystem.IsMacOS() || OperatingSystem.IsIOS();

        IAppleAttestNativeInterop nativeInterop;
        if (useDeviceAttestation)
        {
            // On Apple devices: use the real Security.framework interop so actual native
            // cryptography is exercised (SE-backed or software EC key + ECDSA signing).
            _realNative = new SecurityFrameworkAppleAttestInterop();
            nativeInterop = _realNative;
        }
        else
        {
            // On non-Apple platforms: use a configured mock that returns realistic data
            // and route through the HTTP server-side verification path.
            var mock = new MockAppleAttestNativeInterop
            {
                KeyIdToReturn = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes("test-device"))),
                AttestationObjectToReturn = new byte[512]
            };
            Random.Shared.NextBytes(mock.AttestationObjectToReturn);
            nativeInterop = mock;

            // Server-side path: mock the HTTP call to Apple's verification endpoint.
            var verificationToken = new byte[] { 0x01, 0x02, 0x03, 0x04 };
            var mockResponse = new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new ByteArrayContent(verificationToken)
            };
            var client = new HttpClient(new MockHttpHandler(mockResponse));
            _httpFactoryMock.CreateClient(nameof(AppleSeProvider)).Returns(client);
        }

        var options = Options.Create(new AttestationOptions
        {
            AppleSE = new AppleSeOptions
            {
                VerifyUrl = "https://appattest.apple.com",
                TeamId = "TESTTEAM01",
                AppId = "com.opencert.server",
                UseDeviceAttestation = useDeviceAttestation
            }
        });
        _provider = new AppleSeProvider(_httpFactoryMock, _loggerMock, nativeInterop, options);

        var challenge = new byte[32];
        Random.Shared.NextBytes(challenge);
        _result = await _provider.GenerateAndSignQuoteAsync(null!, challenge);
    }

    [Then(@"the server should successfully verify the object using https:\/\/appattest\.apple\.com and confirm device genuineness")]
    public void ThenTheServerShouldVerify()
    {
        if (_result is null || _result.Length == 0)
            throw new Exception("Expected a non-empty attestation result from Apple provider");
    }

    public void Dispose() => _realNative?.Dispose();
}
